### ISSUE TITLE
INCREDIBLY IMPORTANT typo in readme

### ISSUE THREAD

**Issue by Timmald** [mgpai22/ergo-synced-node#4]
# 'TIS A MATTER OF NATIONAL IMPORTANCE!!!!!!!

In the 8th line of text at the 76th character of the humble readme.md, there is a ***TYPO! (:0)***

This egregious error goes against everything we stand for, and may even go so far as to... *INTERFERE WITH THE VALUES EXPRESSED IN OUR DIVERSITY AND EQUITY STATEMENT*

We hope this dire situation is remedied at once.

**Comment by mgpai22** [comment]
Thank you for your vigilance, good sir! To expedite the correction, could you kindly mark the offending line?
